# Generated by Django 3.2.8 on 2025-11-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='tagline',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
