# Generated by Django 3.2.8 on 2025-10-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20251025_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('DELIVERED', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
